from Base_de_Dados.database import retorna_base_de_dados
from Base_de_Dados.dados.estatisticas import retorna_streak, acresenta_partida
from Base_de_Dados.json_utils import retorna_json, atualiza_json
from Termo_Utils.trata_input import trata_input
from Termo_Utils.config_db import mostra_pede_para_mudar_DB
from Termo_Utils.escolhe_palavra import escolhe_palavra
from Termo_Utils.confere_tentativa import Conferidor_de_Tentativa
