from Termo_Utils.escolhe_palavra import escolhe_palavra
from Termo_Utils.confere_tentativa import Conferidor_de_Tentativa
from Base_de_Dados.database import retorna_base_de_dados
from Base_de_Dados.dados.streak import acresenta_streak, reseta_streak, retorna_streak
from .trata_input import trata_input
