<Manager>:
    DBConf:
        name:"db"

<DBConf>:
    BoxLayout:
        orientation:"vertical"
        Label:
            text:"Qual A Base De Dados Que Deseja Usar?"
        BoxLayout:
            orientation:"vertical"
            Button:
                text:"MySQL"
            Button:
                text:"Pandas"
            Button:
                text:"Pular"
        Label:
            text:""